import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { Chess } from 'chess.js';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.env.CHESS_URL || 'http://127.0.0.1:4178');
await page.locator('canvas').waitFor();
await page.locator('#move-input').fill('e4');
await page.locator('#move-form button').click();
await page.waitForFunction(() => document.querySelector('#move-count').textContent === '2 plies');
assert.match(await page.locator('#status').innerText(), /Your move/);
await page.reload();
await page.waitForFunction(() => document.querySelector('#move-count').textContent === '2 plies');
await page.locator('#undo').click();
assert.equal(await page.locator('#move-count').textContent(), '0 plies');
await page.locator('#move-input').fill('e5');
await page.locator('#move-form button').click();
assert.match(await page.locator('#notice').innerText(), /not legal/);
await page.locator('#side').selectOption('b');
await page.locator('#new').click();
await page.waitForFunction(() => document.querySelector('#move-count').textContent === '1 ply');
assert.match(await page.locator('#human-color').innerText(), /Black/);
await page.locator('#side').selectOption('w');
await page.locator('#new').click();
await page.locator('#confirm-new').click();
await page.locator('#top').click();
await page.waitForTimeout(600);
await page.screenshot({ path: 'chess-top.png' });
await page.mouse.click(600, 680);
assert.match(await page.locator('#selection').textContent(), /pawn on e2/);
await page.mouse.click(600, 550);
await page.waitForFunction(() => document.querySelector('#move-count').textContent === '2 plies');
await page.locator('#undo').click();
await page.locator('#reset-view').click();
await page.waitForTimeout(600);
await page.screenshot({ path: 'chess-preview.png' });
await page.locator('#theme').click();
await page.waitForTimeout(300);
await page.screenshot({ path: 'chess-dark.png' });
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(300);
assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
await page.screenshot({ path: 'chess-mobile.png' });
for (const promotion of ['q', 'r', 'b', 'n']) {
  await page.waitForFunction(() => document.querySelector('#computer-turn').textContent !== 'THINKING');
  const pgn = new Chess('7k/P7/8/8/8/8/8/7K w - - 0 1').pgn();
  await page.evaluate(({ pgn }) => localStorage.setItem('atelier-chess', JSON.stringify({ pgn, human: 'w', level: 'easy' })), { pgn });
  await page.reload();
  await page.locator('#move-input').fill('a7a8');
  await page.locator('#move-form button').click();
  await page.locator(`[data-piece="${promotion}"]`).click();
  await page.waitForFunction(() => document.querySelector('#move-count').textContent !== '0 plies');
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('atelier-chess')));
  assert.match(saved.pgn, new RegExp(`a8=${promotion.toUpperCase()}`));
}
await page.evaluate(() => localStorage.removeItem('atelier-chess'));
assert.deepEqual(errors, []);
console.log('Browser flow passed: human move, computer reply, save/restore, undo, invalid move, play black, restart, views, theme, mobile layout.');
await browser.close();
